# Generated by Django 5.1.15 on 2026-10-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма, руб."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "На рассмотрении"),
                            ("paid", "Выплачено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="accounts.authorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выплата",
                "verbose_name_plural": "Выплаты",
                "db_table": "payouts",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="Royalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royalties",
                        to="accounts.authorprofile",
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royalty",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начисление",
                "verbose_name_plural": "Начисления",
                "db_table": "royalties",
                "ordering": ["-created_at"],
            },
        ),
    ]
