# Generated by Django 4.2 on 2026-03-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.ForeignKey(db_column='Role_id', on_delete=django.db.models.deletion.RESTRICT, to='tracks.role')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('author_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tracks/', verbose_name='Аудиофайл')),
                ('genre', models.ForeignKey(db_column='Genre_id', on_delete=django.db.models.deletion.RESTRICT, to='tracks.genre')),
                ('user', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='tracks.user')),
            ],
            options={
                'db_table': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_value', models.IntegerField()),
                ('track', models.ForeignKey(db_column='Track_id', on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
                ('user', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='tracks.user')),
            ],
            options={
                'db_table': 'Ratings',
                'unique_together': {('user', 'track')},
            },
        ),
    ]
