# Generated by Django 4.2 on 2026-03-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='track',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_tracks', to='tracks.user', verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='track',
            name='moderation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
