FROM python:3.12

# FFmpeg нужен для нарезки 30-секундных демофрагментов
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
