# Generated by Django 5.1.15 on 2026-10-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                ("max_downloads", models.PositiveIntegerField(default=3)),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_link",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на скачивание",
                "verbose_name_plural": "Ссылки на скачивание",
                "db_table": "download_links",
            },
        ),
    ]
